import "./globals.scss";

export const metadata = {
  title: "alver",
  description: "Generated by moein parvizi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={'body'}>{children}</body>
    </html>
  );
}
